import re

from app.schemas.challenge import ValidationRules

""" Utilities for evaluating SQL difficulty and computing scoring factors. """

DIFFICULTY_TO_VALUE = {
    "VERY_EASY": 1,
    "EASY": 2,
    "MEDIUM": 3,
    "HARD": 4,
    "EXPERT": 5,
}

DIFFICULTY_SCORE = {
    "VERY_EASY": 50,
    "EASY": 100,
    "MEDIUM": 200,
    "HARD": 350,
    "EXPERT": 500,
}

VALUE_TO_DIFFICULTY = {v: k for k, v in DIFFICULTY_TO_VALUE.items()}


def get_time_factor(seconds: float) -> float:
    """
    Returns a score multiplier based on solution speed.

    Faster resolutions grant bonus points,
    while slow resolutions apply penalties.
    """
    if seconds < 60:
        return 1.3
    if seconds < 180:
        return 1.15
    if seconds < 300:
        return 1.0
    if seconds < 600:
        return 0.9
    if seconds < 1200:
        return 0.75
    return 0.6


def evaluate_sql_difficulty(sql: str, rules: ValidationRules) -> str:
    """
    Estimates SQL difficulty following the same complexity levels
    used by the procedural challenge generator.

    Difficulty model:

    VERY_EASY
        Simple SELECT from one table.

    EASY
        Single-table SELECT with simple filtering.

    MEDIUM
        JOIN-based queries with at most one additional simple
        construct such as WHERE, DISTINCT or ORDER BY.

    HARD
        JOIN queries combining multiple constructs or using
        aggregation/GROUP BY/HAVING.

    EXPERT
        Queries involving subqueries, EXISTS, correlated queries
        or nested aggregations.
    """

    sql = sql.lower().strip()

    # ============================================================
    # EXPERT
    # ============================================================
    # Subqueries and nested logic are the defining characteristic
    # of the EXPERT generator.
    #
    # We check this first because an expert query may also contain
    # JOIN, WHERE or aggregation.
    # ============================================================

    has_subquery = bool(
        re.search(r"\(\s*select\b", sql)
        or re.search(r"\bexists\s*\(", sql)
        or re.search(r"\bnot\s+exists\s*\(", sql)
    )

    if has_subquery:
        return "EXPERT"

    # ============================================================
    # Detect main SQL constructs
    # ============================================================

    has_join = bool(re.search(r"\bjoin\b", sql))
    has_where = bool(re.search(r"\bwhere\b", sql))
    has_order_by = bool(re.search(r"\border\s+by\b", sql))
    has_distinct = bool(re.search(r"\bselect\s+distinct\b", sql))
    has_group_by = bool(re.search(r"\bgroup\s+by\b", sql))
    has_having = bool(re.search(r"\bhaving\b", sql))
    has_case = bool(re.search(r"\bcase\b", sql))

    has_aggregation = bool(
        re.search(
            r"\b(avg|count|sum|min|max)\s*\(",
            sql
        )
    )

    # ============================================================
    # HARD
    # ============================================================
    # Aggregation-based queries are generated by generate_hard_sql().
    #
    # GROUP BY / HAVING are strong indicators of analytical
    # complexity and therefore immediately place the query in HARD.
    # ============================================================

    if has_group_by or has_having or has_aggregation:
        if has_join:
            return "HARD"

        # Aggregation without JOIN is still more complex than EASY.
        return "HARD"

    # CASE is also considered an advanced construct.
    if has_case:
        return "HARD"

    # ============================================================
    # JOIN-BASED DIFFICULTY
    # ============================================================

    if has_join:

        # Simple additional constructs used by the MEDIUM generator.
        simple_features = 0

        if has_where:
            simple_features += 1

        if has_order_by:
            simple_features += 1

        if has_distinct:
            simple_features += 1

        # --------------------------------------------------------
        # One JOIN + zero/one simple construct = MEDIUM
        # --------------------------------------------------------

        if simple_features <= 1:
            return "MEDIUM"

        # --------------------------------------------------------
        # JOIN + two or more additional constructs = HARD
        # --------------------------------------------------------

        return "HARD"

    # ============================================================
    # EASY
    # ============================================================

    if has_where:
        return "EASY"

    # ============================================================
    # VERY_EASY
    # ============================================================

    return "VERY_EASY"


def get_ordered_difficulties() -> list[str]:
    """ Returns difficulties sorted from easiest to hardest. """
    return sorted(DIFFICULTY_TO_VALUE, key=DIFFICULTY_TO_VALUE.get)

